### ISSUE TITLE
remote: docker: Error response from daemon

### ISSUE THREAD

**Issue by matissg** [dionysio/dokku-nextcloud#1]
Hi,
I'm trying to use your code, however when I do `git push dokku master`
I get this error:
```
remote: docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/sbin/dokku-entrypoint.sh\": permission denied": unknown.
To [my-ip]:nextcloud
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@[my-ip]:nextcloud'
```
**Do you have any idea what could be wrong?**

**Comment by dionysio** [comment]
I see, I made a change that should fix this. Can you try now with the latest code?

**Comment by matissg** [comment]
Thank you. When changed to `RUN ["chmod", "+x", "/sbin/dokku-entrypoint.sh"]` works like charm.

**Comment by dionysio** [comment]
Oh awesome! No problem :)
