### ISSUE TITLE
Nginx default page

### ISSUE THREAD

**Issue by matissg** [dionysio/dokku-nextcloud#2]
I'm trying to install second time Nextcloud as previously I could not succeed. 
At the moment I've done all the steps and have this in my terminal:
```
root@dokku-own-apps:~# dokku config nextcloud
=====> nextcloud env vars
DATABASE_URL:                 postgresql://db_nextcloud:[random-value]@postgres:5432/db_nextcloud
DB_HOST:                      postgres
DB_NAME:                      db_nextcloud
DB_PASS:                      [random-value]
DB_PORT:                      5432
DB_TYPE:                      postgresql
DB_USER:                      db_nextcloud
DOKKU_APP_RESTORE:            1
DOKKU_APP_TYPE:               dockerfile
DOKKU_DOCKERFILE_CMD:         CMD ["php-fpm"]
DOKKU_DOCKERFILE_ENTRYPOINT:  ENTRYPOINT ["/sbin/dokku-entrypoint.sh"]
DOKKU_DOCKERFILE_PORTS:       9000/tcp
DOKKU_PROXY_PORT:             80
DOKKU_PROXY_PORT_MAP:         http:80:9000
GIT_REV:                      [random-value]
NEXTCLOUD_ADMIN_PASSWORD:     [my-pass]
NEXTCLOUD_ADMIN_USER:         [my-user]
POSTGRESQL_URL:               postgresql://db_nextcloud:[random-value]@postgres:5432/db_nextcloud
```
When I open my cloud.mydomain.com URL in  FireFox I get "Welcome to nginx!" page. When I do similar in Chrome, I'm redirected to  my default page, which is different app.
My domains report looks like this:
```
root@dokku-own-apps:~# dokku domains:report nextcloud
=====> nextcloud domains information
       Domains app enabled:           true
       Domains app vhosts:            cloud.[my-domain].com
       Domains global enabled:        true
       Domains global vhosts:         dokku-own-apps
```
In addition I get this as well:
```
root@dokku-own-apps:~# dokku enter nextcloud
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
```
**Do you have any idea why I can't see Nextcloud app, please?**

**Comment by dionysio** [comment]
I don't see anything wrong from the env variables you've posted. I've compared them to mine and they look fine.

If you haven't tried yet, reload your nginx: `nginx -s reload`
Can you please post this file `/home/dokku/nextcloud/nginx.conf` as well?

> root@dokku-own-apps:~# dokku enter nextcloud

Dokku expects the `bin/bash` to be there by default (and it's not there in our container). You can set alternative with this: `dokku config:set --no-restart nextcloud DOKKU_APP_SHELL=/bin/sh`. After that you should be able to enter just fine

**Comment by matissg** [comment]
@dionysio Thank you, however `nginx -s reload` doesn't seem do do anything `dokku nginx -s reload` gives me this one:
```
Usage: dokku nginx[:COMMAND]

Interact with Dokku's Nginx proxy.

Additional commands:
    nginx:access-logs <app> [-t]       Show the nginx access logs for an application (-t follows)
    nginx:build-config <app>           (Re)builds nginx config for given app
    nginx:error-logs <app> [-t]        Show the nginx error logs for an application (-t follows)
    nginx:validate [<app>] [--clean]   Validates and optionally cleans up invalid nginx configurations
```
My `/home/dokku/nextcloud/nginx.conf` looks like this:
```
server {
  listen      [::]:80;
  listen      80;
  server_name [my-domain];
  access_log  /var/log/nginx/nextcloud-access.log;
  error_log   /var/log/nginx/nextcloud-error.log;

  return 301 https://$host:443$request_uri;

}

server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;

  server_name [my-domain];
  access_log  /var/log/nginx/nextcloud-access.log;
  error_log   /var/log/nginx/nextcloud-error.log;

  ssl_certificate     /home/dokku/nextcloud/tls/server.crt;
  ssl_certificate_key /home/dokku/nextcloud/tls/server.key;
  ssl_protocols       TLSv1.2;
  ssl_prefer_server_ciphers on;

  keepalive_timeout   70;

include /home/dokku/nextcloud/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;

upstream nextcloud-9000 {

  server 172.17.0.20:9000;
}
```
`bin/bash` thing worked, thank you... Still, I have no clue why I get Nginx welcome page, not Nextcloud.
I'd be happy if you can help me somehow. Thank you.

**Comment by dionysio** [comment]
Few more things to try:
1. What's the output of `dokku proxy:ports nextcloud`? 
2. if you install cgi-fcgi (the package is called `libfcgi0ldbl` under debian, `fcgi` on centos) and run: `cgi-fcgi -bind -connect 172.17.0.20:9000`. This should return something to this effect:
```
X-Powered-By: PHP/7.2.10
Content-type: text/html; charset=UTF-8
```
3. running `docker ps -a` you see the container running fine, right?

**Comment by dionysio** [comment]
Huh, this might have something to do with the SSL as well (http://dokku.viewdocs.io/dokku/configuration/ssl/#ssl-port-exposure). Try calling `dokku proxy:ports-add nextcloud https:443:9000` first. If that doesn't help, maybe just disable it for now: `dokku certs:remove nextcloud`

**Comment by matissg** [comment]
@dionysio I removed the app and `psql-single-container` and started from scratch following your suggested steps. After pushing the code to container and checking with `docker ps -a` it looks like PSQL is failing:
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                          PORTS               NAMES
[id]        dokku/nextcloud:latest     "/sbin/dokku-entrypo…"   6 minutes ago       Up 6 minutes                    9000/tcp            nextcloud.web.1
[id]        postgres:11.1              "docker-entrypoint.s…"   6 minutes ago       Exited (1) About a minute ago                       psql-single-container
```
In addition I cannot restart Postgres as it is kid of starting and then failing.
My config doesn't look good as well since there is no link to Postgres:
```
=====> nextcloud env vars
DOKKU_APP_RESTORE:            1
DOKKU_APP_TYPE:               dockerfile
DOKKU_DOCKERFILE_CMD:         CMD ["php-fpm"]
DOKKU_DOCKERFILE_ENTRYPOINT:  ENTRYPOINT ["/sbin/dokku-entrypoint.sh"]
DOKKU_DOCKERFILE_PORTS:       9000/tcp
DOKKU_PROXY_PORT:             80
DOKKU_PROXY_PORT_MAP:         http:80:9000
GIT_REV:                      [random]
NEXTCLOUD_ADMIN_PASSWORD:     [pass]
NEXTCLOUD_ADMIN_USER:         [user]
```
Maybe I can somehow modify `dokku-entrypoint` so it is not creating `psql-single-container`, but use my existing Postgres container by just linking app to it?  Then I could: 1) create app, 2) link app to my existing Postgres container, 3) push the code
What do you think?

**Comment by dionysio** [comment]
then:
1. fork this repo
2. change https://github.com/dionysio/dokku-nextcloud/blob/master/app.json#L12 to `"name":"postgres",`
3. figure out how to get the dokku-postgres variables into the ones nextcloud expects here
https://github.com/dionysio/dokku-nextcloud/blob/master/sbin/dokku-entrypoint.sh#L5-L8. I think dokku-postgres creates `DATABASE_URL` so you'd need to split it properly into its parts

**Comment by matissg** [comment]
@dionysio Thank you, however I didn't manage to work Nextcloud with Dokku. I just gave up and created dedicated Digital Ocean instance and installed Nextcloud with snap. Anyway, thank you for helping. Probably there was something in my container config or else. 
I guess you can close this issue.

**Comment by dionysio** [comment]
That's a shame. I've created this after some trial and error but I didn't test it that much, so there might be a bunch of stuff that's broken in here :).

Closing then!
